### ISSUE TITLE
exceptions at checing

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#71] opened 2016-08-16 16:13 UTC
I get the followin errors in the consoles while checking
2016-08-16 18:11:53 Thread-317  ERROR ThriftActionImpl:35 - Error in cc.ecl.action.thrift transport creation
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:356)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
	at cc.codechecker.service.thrift.gen.CodeCheckerDBAccess$Client.send_getRunData(CodeCheckerDBAccess.java:165)
	at cc.codechecker.service.thrift.gen.CodeCheckerDBAccess$Client.getRunData(CodeCheckerDBAccess.java:158)
	at cc.codechecker.api.thrift.run.list.ListRunsActionThriftImpl.runThrift(ListRunsActionThriftImpl.java:38)
	at cc.codechecker.api.thrift.run.list.ListRunsActionThriftImpl.runThrift(ListRunsActionThriftImpl.java:22)
	at cc.ecl.action.thrift.ThriftActionImpl.doRealRun(ThriftActionImpl.java:33)
	at cc.ecl.action.thrift.ThriftActionImpl.doRealRun(ThriftActionImpl.java:17)
	at cc.ecl.action.AbstractActionImpl.doRun(AbstractActionImpl.java:44)
	at cc.ecl.action.Action.runWithImpl(Action.java:64)
	at cc.ecl.action.SimpleActionRunner.requireResult(SimpleActionRunner.java:152)
	at cc.codechecker.api.thrift.result.count.ResultCountActionThriftImpl.runThrift(ResultCountActionThriftImpl.java:54)
	at cc.codechecker.api.thrift.result.count.ResultCountActionThriftImpl.runThrift(ResultCountActionThriftImpl.java:23)
	at cc.ecl.action.thrift.ThriftActionImpl.doRealRun(ThriftActionImpl.java:33)
	at cc.ecl.action.thrift.ThriftActionImpl.doRealRun(ThriftActionImpl.java:17)
	at cc.ecl.action.AbstractActionImpl.doRun(AbstractActionImpl.java:44)
	at cc.ecl.action.Action.runWithImpl(Action.java:64)
	at cc.ecl.action.ActionQueue$QueueItem.runAction(ActionQueue.java:89)
	at cc.ecl.action.SimpleActionRunner.runAction(SimpleActionRunner.java:53)
	at cc.ecl.action.SimpleActionRunner.run(SimpleActionRunner.java:98)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:344)
	... 20 more
2016-08-16 18:11:53 Thread-317  ERROR Action:70 - Exception while running action, treating as COMMUNICATION_ERROR
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:47)
	at cc.codechecker.api.thrift.result.count.ResultCountActionThriftImpl.runThrift(ResultCountActionThriftImpl.java:56)
	at cc.codechecker.api.thrift.result.count.ResultCountActionThriftImpl.runThrift(ResultCountActionThriftImpl.java:23)
	at cc.ecl.action.thrift.ThriftActionImpl.doRealRun(ThriftActionImpl.java:33)
	at cc.ecl.action.thrift.ThriftActionImpl.doRealRun(ThriftActionImpl.java:17)
	at cc.ecl.action.AbstractActionImpl.doRun(AbstractActionImpl.java:44)
	at cc.ecl.action.Action.runWithImpl(Action.java:64)
	at cc.ecl.action.ActionQueue$QueueItem.runAction(ActionQueue.java:89)
	at cc.ecl.action.SimpleActionRunner.runAction(SimpleActionRunner.java:53)
	at cc.ecl.action.SimpleActionRunner.run(SimpleActionRunner.java:98)
	at java.lang.Thread.run(Thread.java:745)

**Comment by whisperity** [comment] 2016-08-16 16:28
Duplicate of #67

**Closed** 2016-08-16 16:33 UTC
